### PR TITLE
Allow priorities to be Floats

### PR DESCRIPTION
**Pull request by hdavid16**
Extended the store and container objects so that priorities are not restricted to being integers.
This is a more general expression of priority which may make it easier at some point to use rank functions (https://github.com/BenLauwens/SimJulia.jl/issues/75).
This also avoids having to normalize (and sometimes scaling) priorities so that they are integer in queueing systems.

### CODE REVIEW

**Comment by hdavid16** [comment]
@BenLauwens can you review this PR? Thanks

**Comment by hdavid16** [comment]
@BenLauwens ?

**Comment by hdavid16** [comment]
Ping @BenLauwens

**Comment by Krastanov** [comment]
@hdavid16 , could you consider resolving the conflicts so we can try to merge this?

**Comment by hdavid16** [comment]
Yes. Will do

**Comment by hdavid16** [comment]
With the migration to JuliaDynamics, there are too many conflicts, despite it being a simple PR. I'll just open a new PR and add the 16 changes where priority is changed from `Int` to `Number`. This will allow passing floats to the priority.

**Pull request closed without merging**
